"""Added the Actualin time and outtime table

Revision ID: 22e77b950561
Revises: a89bdb0cd9b5
Create Date: 2025-01-30 18:37:53.950374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e77b950561'
down_revision = 'a89bdb0cd9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
