"""Added TransportRequest model

Revision ID: 7612df43b10a
Revises: b6d1cfcef8d1
Create Date: 2025-02-10 22:06:43.549216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7612df43b10a'
down_revision = 'b6d1cfcef8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
