"""Mail_status Column added

Revision ID: 78727a33a228
Revises: 7612df43b10a
Create Date: 2025-02-13 10:00:12.330586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78727a33a228'
down_revision = '7612df43b10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('mail_status')

    # ### end Alembic commands ###
