"""Added the Actualin time and outtime table

Revision ID: a89bdb0cd9b5
Revises: 380ca7991ae1
Create Date: 2025-01-29 15:26:49.277313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89bdb0cd9b5'
down_revision = '380ca7991ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Actual_intime', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Actual_outtime', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('Actual_outtime')
        batch_op.drop_column('Actual_intime')

    # ### end Alembic commands ###
