"""Added TransportRequest model

Revision ID: b6d1cfcef8d1
Revises: 22e77b950561
Create Date: 2025-02-10 08:06:06.619947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d1cfcef8d1'
down_revision = '22e77b950561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode_of_transport', sa.String(length=10), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('transport_request')
    # ### end Alembic commands ###
